export const data = {
  requestDto: {
    producer: 'promatic',
    iFrameLink: 'https://string',
    isNew: true,
    name: 'Pudzinator4',
    pictureUrl: 'https://string',
    gameLogo: 'https://string',
    totalReels: 20,
    status: 'ACTIVE',
    slug: 'pudzinator4',
    type: 'SLOT',
    configurations: ['SETTINGS'],
    description: 'good game',
    subType: 'SLOTS',
    theme: 'CELEBRITY',
    minBetAmount: 10,
    betLines: 40,
    minBetLines: 2,
    maxBetLines: 20,
    releaseDate: '27/01/2021',
    unlockLevel: 2,
    unlockGroup: 'NONE',
    langParam: ['DE'],
    ratio: '4:3',
    isFixSize: true,
    isMobileSupport: true,
    gameVolatility: 3,
    bonuses: ['Doubled Scatter Win'],
    mobile: {
      integrationType: 'AIR',
      minAppVersion: '19_0_0',
      maxAppVersion: '22_0_0',
      webUrl: 'string',
      unlockLevel: 3,
      minDeviceMemory: 125,
      mobileGameLogo: 'https://string',
    },
  },
  slugGameQuery: [
    {
      game_name: 'Miss Joker',
      game_slug: 'miss-joker',
    },
    {
      game_name: 'Freezing Fruits',
      game_slug: 'freezing-fruits',
    },
    {
      game_name: 'Disco King',
      game_slug: 'disco-king',
    },
    {
      game_name: 'Red Hot Sevens Deluxe',
      game_slug: 'red-hot-sevens-deluxe',
    },
    {
      game_name: 'Bonus Target',
      game_slug: 'bonus-target',
    },
    {
      game_name: 'Energy 5 Reels',
      game_slug: 'energy-five-reels',
    },
    {
      game_name: 'Wild Saloon',
      game_slug: 'wild-saloon',
    },
    {
      game_name: 'Sin Reels',
      game_slug: 'sin-reels',
    },
    {
      game_name: 'Pudziator',
      game_slug: 'pudziator',
    },
    {
      game_name: 'Bell Spinner',
      game_slug: 'bell-spinner',
    },
    {
      game_name: 'Hussars',
      game_slug: 'hussars',
    },
    {
      game_name: 'Buffalo Wild',
      game_slug: 'buffalo-wild',
    },
    {
      game_name: 'Secret of Amun',
      game_slug: 'secretofamun',
    },
    {
      game_name: 'Wooden Fruits',
      game_slug: 'wooden-fruits',
    },
    {
      game_name: 'Diamond Dazzle',
      game_slug: 'diamond-dazzle',
    },
    {
      game_name: "Devil's Fruits",
      game_slug: 'devils-fruits',
    },
    {
      game_name: 'Poseidon’s Gold Deluxe',
      game_slug: 'poseidons-gold-deluxe',
    },
    {
      game_name: 'The Wild Book',
      game_slug: 'the-wild-book',
    },
    {
      game_name: 'Jumping Fruits',
      game_slug: 'jumping-fruits',
    },
    {
      game_name: 'Galaxy Gems',
      game_slug: 'galaxy-gems',
    },
  ],
  partnerData: [
    {
      id: '2f03715b5bca3a4b57f771cc903c9ebe::partner',
      partners: {
        active: true,
        address: '789 Street',
        city: 'Warsaw',
        country: 'Poland',
        created_at: 1604145207000,
        email: 'netent@partner.com',
        game_count: 6,
        name: 'netent',
        partner_logo:
          'https://socialgames-partner.s3.eu-central-1.amazonaws.com/logo/netent%40partner.com/1609855059092_1609569139927_1600773154390_producer-2.png',
        phone: '356987489',
        secret_key: '2831bbfe2e2438504eca6ad56c9002d4',
        type: 'GLOBAL',
        updated_at: 1610017062883,
        zip_code: 'WA0987',
      },
    },
    {
      id: '702bf14b2c6e5fcca6659248332a4af5::partner',
      partners: {
        active: true,
        address: '786 Street',
        city: 'Warsaw',
        country: 'Poland',
        created_at: 1607427652253,
        email: 'promatic@partner.com',
        game_count: 14,
        name: 'promatic',
        partner_logo:
          'https://socialgames-partner.s3.eu-central-1.amazonaws.com/logo/promatic%40partner.com/1607427650195_1600773800779_producer-1.png',
        phone: '234562345',
        secret_key: '55451c0c8ee59cce7e1bbd1f1633aa5f',
        type: 'GLOBAL',
        updated_at: 1610520875444,
        zip_code: 'WA0987',
      },
    },
  ],
  mappedGame: {
    id: '5e9a3239-8431-4238-ab8e-592cf36d0e02',
    producer: 'promatic',
    game_iframe_link: 'https://string',
    is_new_game: true,
    game_name: 'Pudziator4',
    game_picture_url: 'https://string',
    game_logo: 'https://string',
    total_reels: 20,
    game_status: 'ACTIVE',
    game_activated_at: 1609403792978,
    game_slug: 'pudzinator4',
    configurations: [],
    game_description: 'Good game',
    game_theme: 'CELEBRITY',
    min_bet_amount: 10,
    bet_lines: 40,
    min_bet_lines: 2,
    max_bet_lines: 20,
    release_date: '12-30-2020',
    unlock_level: 2,
    unlock_group: 'NONE',
    lang_param: ['DE'],
    ratio: '4:3',
    is_fix_size: true,
    is_mobile_support: true,
    created: 1609327253964,
    updated: null,
    game_volatility: 3,
    bonuses: ['Doubled Scatter Win'],
    mobile: {
      integration_type: 'AIR',
      asset_path:
        'https://stech-games-app-stage.pgext1.net/h5/index.html?gameId=00050370',
      web_url:
        'https://stech-games-app-stage.pgext1.net/h5/index.html?gameId=00050370',
      unlock_level: 1,
      mobile_game_logo:
        'https://socialgames-game.s3.eu-central-1.amazonaws.com/Pudziator/background-image/1609327247923_pudziator.png',
    },
  },
  gameResponse: {
    id: '5e9a3239-8431-4238-ab8e-592cf36d0e02',
    producer: 'promatic',
    iFrameLink:
      'https://stech-games-app-stage.pgext1.net/h5/index.html?gameId=00050370',
    isNew: true,
    name: 'Pudziator',
    pictureUrl:
      'https://socialgames-game.s3.eu-central-1.amazonaws.com/Pudziator/background-image/1609327247923_pudziator.png',
    gameLogo:
      'https://socialgames-game.s3.eu-central-1.amazonaws.com/Pudziator/background-image/1609327247923_pudziator.png',
    totalReels: 5,
    status: 'ACTIVE',
    gameActivatedAt: '2020-12-31T08:36:32.978Z',
    slug: 'pudziator',
    configurations: [],
    description:
      'All wins pay left to right on adjacent reels, starting from leftmost reel, on available win lines.',
    theme: 'CELEBRITY',
    minBetAmount: 20,
    betLines: 27,
    minBetLines: 27,
    maxBetLines: 27,
    releaseDate: '12-30-2020',
    unlockLevel: 1,
    unlockGroup: 'NONE',
    langParam: [],
    ratio: '4:3',
    isFixSize: true,
    isMobileSupport: true,
    createdDate: '2020-12-30T11:20:53.964Z',
    updatedDate: '',
    gameVolatility: '3/5',
    bonuses: ['Doubled Scatter Win'],
    mobile: {
      integrationType: 'AIR',
      webUrl:
        'https://stech-games-app-stage.pgext1.net/h5/index.html?gameId=00050370',
      unlockLevel: 1,
      mobileGameLogo:
        'https://socialgames-game.s3.eu-central-1.amazonaws.com/Pudziator/background-image/1609327247923_pudziator.png',
    },
    isPopular: false,
    isGuestGame: false,
  },
};

export const GameMapper = (payload: Object) => {
  return data.mappedGame;
};
